

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."price" AS ENUM (
    'NUMERIC(10, 2)'
);


ALTER TYPE "public"."price" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."count_coupon_paid_use"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  -- Count only the transition INTO 'Paid' (repeat callback hits and other
  -- status churn don't recount).
  if new.coupon_code is not null
     and new.status = 'Paid'
     and coalesce(old.status, '') <> 'Paid' then
    update coupons
      set times_paid = times_paid + 1
      where upper(code) = upper(new.coupon_code);
  end if;
  return new;
end
$$;


ALTER FUNCTION "public"."count_coupon_paid_use"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."affiliates_tracking" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "affiliate_id" "text" NOT NULL,
    "stage" "text" NOT NULL,
    "data" "json",
    "user_id" "text" NOT NULL
);


ALTER TABLE "public"."affiliates_tracking" OWNER TO "postgres";


ALTER TABLE "public"."affiliates_tracking" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."affiliates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."artists" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "name_english" "text",
    "preview_text" "text",
    "image_url" "text",
    "image_width" integer,
    "image_height" integer,
    "bio" "jsonb",
    "seo_title" "text",
    "meta_description" "text",
    "meta_tags" "text",
    "featured_order" integer,
    "is_active" boolean DEFAULT true NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "hero_video_url" "text",
    "banners" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "gallery" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "videos" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "art_image_url" "text",
    "art_color_index" integer,
    "art_shape_index" integer,
    "art_image_scale" real,
    "art_bg_scale" real,
    "art_image_offset_x" real,
    "art_image_offset_y" real
);


ALTER TABLE "public"."artists" OWNER TO "postgres";


ALTER TABLE "public"."artists" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."artists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."blog_posts" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "title" "text",
    "preview_text" "text",
    "by_who" "text",
    "image_url" "text",
    "image_width" integer,
    "image_height" integer,
    "main_content" "jsonb",
    "seo_title_tag" "text",
    "meta_description" "text",
    "meta_tags" "text",
    "display_order" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "art_image_url" "text",
    "art_color_index" integer,
    "art_shape_index" integer,
    "art_image_scale" real,
    "art_bg_scale" real,
    "art_image_offset_x" real,
    "art_image_offset_y" real
);


ALTER TABLE "public"."blog_posts" OWNER TO "postgres";


ALTER TABLE "public"."blog_posts" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."blog_posts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "name_english" "text",
    "image_url" "text",
    "subtitle" "text",
    "tag" "text",
    "sport" "text",
    "member_ids" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "link_url" "text",
    "display_order" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "art_image_url" "text",
    "art_color_index" integer,
    "art_shape_index" integer,
    "art_image_scale" real,
    "art_bg_scale" real,
    "art_image_offset_x" real,
    "art_image_offset_y" real
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."coupons" (
    "id" bigint NOT NULL,
    "code" "text" NOT NULL,
    "discount_type" "text" NOT NULL,
    "discount_value" numeric NOT NULL,
    "event_id" bigint,
    "valid_until" "date",
    "max_uses" integer,
    "times_used" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "times_paid" integer DEFAULT 0 NOT NULL,
    "partner_tracking_code" "text",
    CONSTRAINT "coupons_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['percent'::"text", 'fixed'::"text"]))),
    CONSTRAINT "coupons_discount_value_check" CHECK (("discount_value" > (0)::numeric))
);


ALTER TABLE "public"."coupons" OWNER TO "postgres";


ALTER TABLE "public"."coupons" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."coupons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "date" "date" NOT NULL,
    "location" "json",
    "description" "text" NOT NULL,
    "tickets_and_rates" "json"[] NOT NULL,
    "card_image_url" "text",
    "map_image_url" "text",
    "def_date_depart" "date" NOT NULL,
    "def_date_return" "date" NOT NULL,
    "usual_price" smallint NOT NULL,
    "base_flight_price" smallint NOT NULL,
    "base_hotel_price" smallint NOT NULL,
    "name_english" "text",
    "is_prioritized" boolean DEFAULT false,
    "is_deleted" "date",
    "tags" "text",
    "type" "text" DEFAULT 'music_event'::"text" NOT NULL,
    "skip_flight" boolean DEFAULT false,
    "tx_excluded_sections" "text"[],
    "skip_flight_markup" numeric,
    "event_additional_markup" smallint,
    "comp_pricing" "jsonb",
    "art_image_url" "text",
    "art_color_index" smallint,
    "art_shape_index" smallint,
    "art_image_scale" real,
    "art_bg_scale" real,
    "art_image_offset_x" real,
    "art_image_offset_y" real,
    "markup_ticket" numeric,
    "markup_flight" numeric,
    "markup_hotel" numeric,
    "skip_hotel_markup" numeric,
    "ticket_only_markup" numeric
);


ALTER TABLE "public"."events" OWNER TO "postgres";


COMMENT ON COLUMN "public"."events"."base_flight_price" IS 'המחיר של הטיסה הישירה הסטנדרטית לאדם בתאריכים הדיפולטים (צריך להימצא בחיפוש בכל בוקר)';



COMMENT ON COLUMN "public"."events"."base_hotel_price" IS 'המחיר למלון לאדם בחדר זוכי';



ALTER TABLE "public"."events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."flights" (
    "id" bigint NOT NULL,
    "initial_quantity" integer NOT NULL,
    "consumed_quantity" integer DEFAULT 0 NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "price" numeric(10,2) NOT NULL,
    "duration" interval NOT NULL,
    "stops" integer NOT NULL,
    "airline_code" character varying(3) NOT NULL,
    "outbound_departure_time" timestamp without time zone NOT NULL,
    "outbound_departure_airport" character varying(3) NOT NULL,
    "outbound_arrival_airport" character varying(3) NOT NULL,
    "outbound_arrival_time" timestamp without time zone NOT NULL,
    "outbound_duration" interval NOT NULL,
    "outbound_check_bags_included" boolean NOT NULL,
    "outbound_cabin_bags_included" boolean NOT NULL,
    "outbound_flight_number" character varying(10) NOT NULL,
    "inbound_departure_time" timestamp without time zone NOT NULL,
    "inbound_departure_airport" character varying(3) NOT NULL,
    "inbound_arrival_airport" character varying(3) NOT NULL,
    "inbound_arrival_time" timestamp without time zone NOT NULL,
    "inbound_duration" interval NOT NULL,
    "inbound_check_bags_included" boolean NOT NULL,
    "inbound_cabin_bags_included" boolean NOT NULL,
    "inbound_flight_number" character varying(10) NOT NULL,
    "metadata_iata" character varying(3) NOT NULL,
    "metadata_name" "text" NOT NULL,
    "metadata_logo" "text" NOT NULL,
    "event_ids" integer[] DEFAULT '{}'::integer[] NOT NULL,
    CONSTRAINT "flights_stops_check" CHECK (("stops" = 0))
);


ALTER TABLE "public"."flights" OWNER TO "postgres";


ALTER TABLE "public"."flights" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flights_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."football_teams" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "name_english" "text",
    "preview_text" "text",
    "image_url" "text",
    "image_width" integer,
    "image_height" integer,
    "bio" "jsonb",
    "seo_title" "text",
    "meta_description" "text",
    "meta_tags" "text",
    "featured_order" integer,
    "is_active" boolean DEFAULT true NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "hero_video_url" "text",
    "banners" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "gallery" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "videos" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "art_image_url" "text",
    "art_color_index" integer,
    "art_shape_index" integer,
    "art_image_scale" real,
    "art_bg_scale" real,
    "art_image_offset_x" real,
    "art_image_offset_y" real,
    "logo_url" "text"
);


ALTER TABLE "public"."football_teams" OWNER TO "postgres";


ALTER TABLE "public"."football_teams" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."football_teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."hotels" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "_id" "text" NOT NULL,
    "hid" bigint NOT NULL,
    "name" "text" NOT NULL,
    "address" "text" NOT NULL,
    "latitude" numeric NOT NULL,
    "longitude" numeric NOT NULL,
    "star_rating" smallint NOT NULL,
    "amenity_groups" "jsonb" NOT NULL,
    "images_ext" "jsonb" NOT NULL,
    "room_groups" "jsonb" NOT NULL,
    "city" "text" NOT NULL,
    "kind" "text",
    "guest_rating" numeric,
    "guest_review_count" integer,
    "guest_detailed_ratings" "jsonb",
    "guest_rating_updated_at" timestamp with time zone
);


ALTER TABLE "public"."hotels" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."live_events" (
    "event_id" integer NOT NULL,
    "event_name" character varying NOT NULL,
    "event_name_heb" character varying,
    "show_date" timestamp with time zone NOT NULL,
    "is_show_date_finale" boolean DEFAULT false,
    "show_date_remarks" "text",
    "street_address" "text",
    "street_address_heb" "text",
    "city_id" integer,
    "city_name" character varying,
    "country_id" integer,
    "country_name" character varying,
    "iata" character varying(3),
    "passport_required" boolean DEFAULT false,
    "venue_map_url" "text",
    "venue_map_heb_url" "text",
    "currency" integer NOT NULL,
    "stop_selling_margin" integer DEFAULT 0,
    "event_type" character varying NOT NULL,
    "primary_category" character varying,
    "categories" "jsonb",
    "performers" "jsonb",
    "venues" "jsonb",
    "ticket_categories" "jsonb",
    "last_synced" timestamp with time zone DEFAULT "now"(),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."live_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."locations" (
    "id" integer NOT NULL,
    "name" character varying NOT NULL,
    "latitude" numeric(10,8) NOT NULL,
    "longitude" numeric(11,8) NOT NULL,
    "city_iata" character varying(3),
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "country_code" "text"
);


ALTER TABLE "public"."locations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."locations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."locations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."locations_id_seq" OWNED BY "public"."locations"."id";



CREATE TABLE IF NOT EXISTS "public"."offline_hotel_rooms" (
    "id" bigint NOT NULL,
    "hotel_id" bigint NOT NULL,
    "room_type" "text" NOT NULL,
    "price" numeric NOT NULL,
    "meal_plan" "text",
    "last_cancellation_date" "date",
    "supplier" "text",
    "is_booked" boolean DEFAULT false NOT NULL,
    "order_no" "text",
    "acc_no" "text",
    "reservation_id" bigint,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."offline_hotel_rooms" OWNER TO "postgres";


ALTER TABLE "public"."offline_hotel_rooms" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."offline_hotel_rooms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."offline_hotels" (
    "id" integer NOT NULL,
    "hotel_name" "text" NOT NULL,
    "city" "text" NOT NULL,
    "check_in" "date" NOT NULL,
    "check_out" "date" NOT NULL,
    "price" numeric(10,2) NOT NULL,
    "room_type" "text" NOT NULL,
    "num_rooms" integer DEFAULT 1 NOT NULL,
    "consumed_rooms" integer DEFAULT 0 NOT NULL,
    "meal_plan" "text",
    "notes" "text",
    "event_ids" integer[] DEFAULT '{}'::integer[] NOT NULL,
    "flight_ids" integer[] DEFAULT '{}'::integer[] NOT NULL,
    "is_deleted" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "hid" integer,
    "last_cancellation_date" "date",
    "guest_rating" numeric,
    "guest_review_count" integer
);


ALTER TABLE "public"."offline_hotels" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."offline_hotels_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."offline_hotels_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."offline_hotels_id_seq" OWNED BY "public"."offline_hotels"."id";



CREATE TABLE IF NOT EXISTS "public"."p1_events" (
    "event_id" character varying NOT NULL,
    "title" character varying NOT NULL,
    "title_english" character varying NOT NULL,
    "category" character varying NOT NULL,
    "series_id" character varying,
    "series_name" character varying,
    "has_available_tickets" boolean DEFAULT true,
    "is_advertisable" boolean DEFAULT true,
    "date_start" timestamp with time zone NOT NULL,
    "date_end" timestamp with time zone,
    "date_confirmed" boolean DEFAULT false,
    "stock" integer DEFAULT 0,
    "venue_name" character varying NOT NULL,
    "venue_city" character varying NOT NULL,
    "venue_country_code" character varying(2),
    "venue_latitude" numeric(10,8),
    "venue_longitude" numeric(11,8),
    "compare_price_ticket_only" numeric(10,2),
    "compare_price_ticket_hotel" numeric(10,2),
    "checkout_link" "text",
    "tickets" "jsonb",
    "last_synced" timestamp with time zone DEFAULT "now"(),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."p1_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."partners" (
    "created_at" "date" NOT NULL,
    "partner_tracking_code" "text" NOT NULL,
    "email" "text" NOT NULL,
    "password" "text" NOT NULL,
    "commission" smallint DEFAULT '0'::smallint NOT NULL,
    "user_discount" smallint DEFAULT '0'::smallint NOT NULL,
    "supplier_number" bigint,
    "name_hebrew" "text",
    "type" character varying DEFAULT 'affiliate'::character varying,
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."partners" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reservations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "main_contact_first_name" "text" NOT NULL,
    "main_contact_last_name" "text" NOT NULL,
    "main_contact_phone_number" "text" NOT NULL,
    "main_contact_email" "text" NOT NULL,
    "more_pax_info" "json"[],
    "event_order_info" "json" NOT NULL,
    "flight_order_info" "json" NOT NULL,
    "hotel_order_info" "json" NOT NULL,
    "user_shown_price" integer NOT NULL,
    "aff_partner_tracking_code" "text",
    "event_id" bigint NOT NULL,
    "payment_info" "json",
    "status" "text" DEFAULT 'Pending'::"text" NOT NULL,
    "comments" "text",
    "booking_reference" "text",
    "accounting_number" bigint,
    "final_purchase_price_ils" integer,
    "exchange_rate_usd_ils_100" smallint,
    "confirmation_email_sent" boolean DEFAULT false,
    "gtmIdnts" "jsonb",
    "offline_flight_id" bigint,
    "offline_hotel_id" bigint,
    "offline_flight_cost" numeric(10,2),
    "offline_hotel_cost" numeric(10,2),
    "offline_hotel_ids" integer[],
    "coupon_code" "text",
    "coupon_discount_usd" numeric
);


ALTER TABLE "public"."reservations" OWNER TO "postgres";


COMMENT ON COLUMN "public"."reservations"."offline_flight_id" IS 'FK to flights.id when the reservation consumed an offline (Mega) flight row.';



COMMENT ON COLUMN "public"."reservations"."offline_hotel_id" IS 'FK to offline_hotels.id when the reservation consumed a Mega offline hotel row.';



COMMENT ON COLUMN "public"."reservations"."offline_flight_cost" IS 'Real per-traveler inventory cost from flights.price at booking time (USD).';



COMMENT ON COLUMN "public"."reservations"."offline_hotel_cost" IS 'Real per-room inventory cost from offline_hotels.price at booking time (USD).';



COMMENT ON COLUMN "public"."reservations"."offline_hotel_ids" IS 'Offline hotel row IDs matched to this reservation. May repeat when a single row covers multiple requested rooms. offline_hotel_id (singular) is kept for backwards compatibility and holds offline_hotel_ids[0].';



ALTER TABLE "public"."reservations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reservations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tixstock_events" (
    "event_id" character varying NOT NULL,
    "event_name" character varying NOT NULL,
    "show_date" timestamp with time zone NOT NULL,
    "event_status" character varying,
    "venue_name" character varying,
    "city_name" character varying,
    "country_code" character varying(2),
    "venue_data" "jsonb",
    "venue_map_url" "text",
    "category_name" character varying,
    "sub_categories" "jsonb",
    "performers" "jsonb",
    "last_synced" timestamp with time zone DEFAULT "now"(),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."tixstock_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."xs2e_events" (
    "event_id" character varying NOT NULL,
    "event_name" character varying NOT NULL,
    "event_name_heb" character varying,
    "date_start" timestamp with time zone NOT NULL,
    "date_stop" timestamp with time zone NOT NULL,
    "event_status" character varying NOT NULL,
    "tournament_id" character varying NOT NULL,
    "tournament_name" character varying NOT NULL,
    "tournament_name_heb" character varying,
    "venue_id" character varying NOT NULL,
    "venue_name" character varying NOT NULL,
    "venue_name_heb" character varying,
    "city" character varying,
    "latitude" numeric(10,8),
    "longitude" numeric(11,8),
    "date_confirmed" boolean DEFAULT false,
    "hometeam_name" character varying,
    "visiting_name" character varying,
    "created" timestamp with time zone,
    "updated" timestamp with time zone,
    "event_description" "text",
    "event_description_heb" "text",
    "min_ticket_price_eur" numeric(10,2),
    "max_ticket_price_eur" numeric(10,2),
    "slug" character varying,
    "number_of_tickets" integer,
    "sales_periods" "jsonb",
    "is_popular" boolean DEFAULT false,
    "location_id" character varying,
    "iso_country" character varying(3),
    "sport_type" character varying,
    "season" character varying,
    "tournament_type" character varying,
    "date_start_main_event" timestamp with time zone,
    "date_stop_main_event" timestamp with time zone,
    "hometeam_id" character varying,
    "visiting_id" character varying,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."xs2e_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."xs2e_sports" (
    "sport_id" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."xs2e_sports" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."xs2e_tournaments" (
    "tournament_id" character varying NOT NULL,
    "official_name" character varying NOT NULL,
    "season" character varying NOT NULL,
    "tournament_type" character varying NOT NULL,
    "region" character varying NOT NULL,
    "sport_type" character varying NOT NULL,
    "date_start" timestamp with time zone NOT NULL,
    "date_stop" timestamp with time zone NOT NULL,
    "slug" character varying,
    "number_events" integer,
    "created" timestamp with time zone,
    "updated" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."xs2e_tournaments" OWNER TO "postgres";


ALTER TABLE ONLY "public"."locations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."locations_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."offline_hotels" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."offline_hotels_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."affiliates_tracking"
    ADD CONSTRAINT "affiliates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."artists"
    ADD CONSTRAINT "artists_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."artists"
    ADD CONSTRAINT "artists_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."blog_posts"
    ADD CONSTRAINT "blog_posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blog_posts"
    ADD CONSTRAINT "blog_posts_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."coupons"
    ADD CONSTRAINT "coupons_code_key" UNIQUE ("code");



ALTER TABLE ONLY "public"."coupons"
    ADD CONSTRAINT "coupons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flights"
    ADD CONSTRAINT "flights_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."football_teams"
    ADD CONSTRAINT "football_teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."football_teams"
    ADD CONSTRAINT "football_teams_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."hotels"
    ADD CONSTRAINT "hotels_pkey" PRIMARY KEY ("hid");



ALTER TABLE ONLY "public"."live_events"
    ADD CONSTRAINT "live_events_pkey" PRIMARY KEY ("event_id");



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."offline_hotel_rooms"
    ADD CONSTRAINT "offline_hotel_rooms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."offline_hotels"
    ADD CONSTRAINT "offline_hotels_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."p1_events"
    ADD CONSTRAINT "p1_events_pkey" PRIMARY KEY ("event_id");



ALTER TABLE ONLY "public"."partners"
    ADD CONSTRAINT "partners_pkey" PRIMARY KEY ("partner_tracking_code");



ALTER TABLE ONLY "public"."partners"
    ADD CONSTRAINT "partners_user_id_key" UNIQUE ("partner_tracking_code");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_booking_reference_key" UNIQUE ("booking_reference");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tixstock_events"
    ADD CONSTRAINT "tixstock_events_pkey" PRIMARY KEY ("event_id");



ALTER TABLE ONLY "public"."xs2e_events"
    ADD CONSTRAINT "xs2e_events_pkey" PRIMARY KEY ("event_id");



ALTER TABLE ONLY "public"."xs2e_sports"
    ADD CONSTRAINT "xs2e_sports_pkey" PRIMARY KEY ("sport_id");



ALTER TABLE ONLY "public"."xs2e_tournaments"
    ADD CONSTRAINT "xs2e_tournaments_pkey" PRIMARY KEY ("tournament_id");



CREATE UNIQUE INDEX "hotels_hid_uidx" ON "public"."hotels" USING "btree" ("hid");



CREATE INDEX "hotels_star_kind_idx" ON "public"."hotels" USING "btree" ("star_rating", "kind");



CREATE INDEX "idx_artists_active" ON "public"."artists" USING "btree" ("is_active") WHERE ("is_deleted" = false);



CREATE INDEX "idx_artists_featured" ON "public"."artists" USING "btree" ("featured_order");



CREATE INDEX "idx_artists_name_english" ON "public"."artists" USING "btree" ("name_english");



CREATE INDEX "idx_blog_active" ON "public"."blog_posts" USING "btree" ("is_active") WHERE ("is_deleted" = false);



CREATE INDEX "idx_categories_active" ON "public"."categories" USING "btree" ("is_active") WHERE ("is_deleted" = false);



CREATE INDEX "idx_categories_order" ON "public"."categories" USING "btree" ("display_order");



CREATE INDEX "idx_categories_slug" ON "public"."categories" USING "btree" ("slug");



CREATE INDEX "idx_flights_event_ids" ON "public"."flights" USING "gin" ("event_ids");



CREATE INDEX "idx_football_active" ON "public"."football_teams" USING "btree" ("is_active") WHERE ("is_deleted" = false);



CREATE INDEX "idx_football_featured" ON "public"."football_teams" USING "btree" ("featured_order");



CREATE INDEX "idx_football_name_english" ON "public"."football_teams" USING "btree" ("name_english");



CREATE INDEX "idx_hotels_hid" ON "public"."hotels" USING "btree" ("hid");



CREATE INDEX "idx_live_events_city_id" ON "public"."live_events" USING "btree" ("city_id");



CREATE INDEX "idx_live_events_country_id" ON "public"."live_events" USING "btree" ("country_id");



CREATE INDEX "idx_live_events_currency" ON "public"."live_events" USING "btree" ("currency");



CREATE INDEX "idx_live_events_event_type" ON "public"."live_events" USING "btree" ("event_type");



CREATE INDEX "idx_live_events_is_active" ON "public"."live_events" USING "btree" ("is_active");



CREATE INDEX "idx_live_events_name_search" ON "public"."live_events" USING "gin" ("to_tsvector"('"english"'::"regconfig", ("event_name")::"text"));



CREATE INDEX "idx_live_events_primary_category" ON "public"."live_events" USING "btree" ("primary_category");



CREATE INDEX "idx_live_events_show_date" ON "public"."live_events" USING "btree" ("show_date");



CREATE INDEX "idx_locations_city_iata" ON "public"."locations" USING "btree" ("city_iata");



CREATE INDEX "idx_locations_latitude" ON "public"."locations" USING "btree" ("latitude");



CREATE INDEX "idx_locations_longitude" ON "public"."locations" USING "btree" ("longitude");



CREATE INDEX "idx_offline_hotel_rooms_hotel_id" ON "public"."offline_hotel_rooms" USING "btree" ("hotel_id");



CREATE INDEX "idx_offline_hotel_rooms_is_booked" ON "public"."offline_hotel_rooms" USING "btree" ("is_booked");



CREATE INDEX "idx_offline_hotels_event_ids" ON "public"."offline_hotels" USING "gin" ("event_ids");



CREATE INDEX "idx_offline_hotels_flight_ids" ON "public"."offline_hotels" USING "gin" ("flight_ids");



CREATE INDEX "idx_p1_events_category" ON "public"."p1_events" USING "btree" ("category");



CREATE INDEX "idx_p1_events_date_start" ON "public"."p1_events" USING "btree" ("date_start");



CREATE INDEX "idx_p1_events_has_tickets" ON "public"."p1_events" USING "btree" ("has_available_tickets");



CREATE INDEX "idx_p1_events_is_active" ON "public"."p1_events" USING "btree" ("is_active");



CREATE INDEX "idx_p1_events_is_advertisable" ON "public"."p1_events" USING "btree" ("is_advertisable");



CREATE INDEX "idx_p1_events_series_name" ON "public"."p1_events" USING "btree" ("series_name");



CREATE INDEX "idx_p1_events_title_search" ON "public"."p1_events" USING "gin" ("to_tsvector"('"english"'::"regconfig", ("title")::"text"));



CREATE INDEX "idx_p1_events_venue_city" ON "public"."p1_events" USING "btree" ("venue_city");



CREATE INDEX "idx_p1_events_venue_country" ON "public"."p1_events" USING "btree" ("venue_country_code");



CREATE INDEX "idx_reservations_offline_flight_id" ON "public"."reservations" USING "btree" ("offline_flight_id") WHERE ("offline_flight_id" IS NOT NULL);



CREATE INDEX "idx_reservations_offline_hotel_id" ON "public"."reservations" USING "btree" ("offline_hotel_id") WHERE ("offline_hotel_id" IS NOT NULL);



CREATE INDEX "idx_xs2e_events_date_start" ON "public"."xs2e_events" USING "btree" ("date_start");



CREATE INDEX "idx_xs2e_events_popular" ON "public"."xs2e_events" USING "btree" ("is_popular");



CREATE INDEX "idx_xs2e_events_status" ON "public"."xs2e_events" USING "btree" ("event_status");



CREATE INDEX "idx_xs2e_events_tournament_id" ON "public"."xs2e_events" USING "btree" ("tournament_id");



CREATE INDEX "idx_xs2e_events_venue_id" ON "public"."xs2e_events" USING "btree" ("venue_id");



CREATE INDEX "idx_xs2e_sports_sport_id" ON "public"."xs2e_sports" USING "btree" ("sport_id");



CREATE INDEX "idx_xs2e_tournaments_date_start" ON "public"."xs2e_tournaments" USING "btree" ("date_start");



CREATE INDEX "idx_xs2e_tournaments_date_stop" ON "public"."xs2e_tournaments" USING "btree" ("date_stop");



CREATE INDEX "idx_xs2e_tournaments_sport_type" ON "public"."xs2e_tournaments" USING "btree" ("sport_type");



CREATE INDEX "idx_xs2e_tournaments_tournament_id" ON "public"."xs2e_tournaments" USING "btree" ("tournament_id");



CREATE OR REPLACE TRIGGER "coupon_paid_counter" AFTER UPDATE OF "status" ON "public"."reservations" FOR EACH ROW EXECUTE FUNCTION "public"."count_coupon_paid_use"();



CREATE OR REPLACE TRIGGER "live_events_updated_at" BEFORE UPDATE ON "public"."live_events" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "p1_events_updated_at" BEFORE UPDATE ON "public"."p1_events" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_locations_updated_at" BEFORE UPDATE ON "public"."locations" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_xs2e_events_updated_at" BEFORE UPDATE ON "public"."xs2e_events" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_xs2e_sports_updated_at" BEFORE UPDATE ON "public"."xs2e_sports" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_xs2e_tournaments_updated_at" BEFORE UPDATE ON "public"."xs2e_tournaments" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."affiliates_tracking"
    ADD CONSTRAINT "affiliates_tracking_affiliate_id_fkey" FOREIGN KEY ("affiliate_id") REFERENCES "public"."partners"("partner_tracking_code");



ALTER TABLE ONLY "public"."coupons"
    ADD CONSTRAINT "coupons_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id");



ALTER TABLE ONLY "public"."coupons"
    ADD CONSTRAINT "coupons_partner_tracking_code_fkey" FOREIGN KEY ("partner_tracking_code") REFERENCES "public"."partners"("partner_tracking_code") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."offline_hotel_rooms"
    ADD CONSTRAINT "offline_hotel_rooms_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "public"."offline_hotels"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_offline_flight_id_fkey" FOREIGN KEY ("offline_flight_id") REFERENCES "public"."flights"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_offline_hotel_id_fkey" FOREIGN KEY ("offline_hotel_id") REFERENCES "public"."offline_hotels"("id") ON DELETE SET NULL;



CREATE POLICY "Enable read access for all users" ON "public"."xs2e_events" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."xs2e_sports" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."xs2e_tournaments" FOR SELECT USING (true);



ALTER TABLE "public"."affiliates_tracking" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."artists" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blog_posts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."coupons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."flights" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."football_teams" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hotels" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."live_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."locations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."offline_hotel_rooms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."offline_hotels" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."p1_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."partners" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reservations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tixstock_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."xs2e_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."xs2e_sports" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."xs2e_tournaments" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

















































































































































































GRANT ALL ON FUNCTION "public"."count_coupon_paid_use"() TO "anon";
GRANT ALL ON FUNCTION "public"."count_coupon_paid_use"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."count_coupon_paid_use"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."affiliates_tracking" TO "anon";
GRANT ALL ON TABLE "public"."affiliates_tracking" TO "authenticated";
GRANT ALL ON TABLE "public"."affiliates_tracking" TO "service_role";



GRANT ALL ON SEQUENCE "public"."affiliates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."affiliates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."affiliates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."artists" TO "anon";
GRANT ALL ON TABLE "public"."artists" TO "authenticated";
GRANT ALL ON TABLE "public"."artists" TO "service_role";



GRANT ALL ON SEQUENCE "public"."artists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."artists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."artists_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."blog_posts" TO "anon";
GRANT ALL ON TABLE "public"."blog_posts" TO "authenticated";
GRANT ALL ON TABLE "public"."blog_posts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."blog_posts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."blog_posts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."blog_posts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."coupons" TO "anon";
GRANT ALL ON TABLE "public"."coupons" TO "authenticated";
GRANT ALL ON TABLE "public"."coupons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."coupons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."coupons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."coupons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";
GRANT ALL ON TABLE "public"."events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."flights" TO "anon";
GRANT ALL ON TABLE "public"."flights" TO "authenticated";
GRANT ALL ON TABLE "public"."flights" TO "service_role";



GRANT ALL ON SEQUENCE "public"."flights_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flights_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flights_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."football_teams" TO "anon";
GRANT ALL ON TABLE "public"."football_teams" TO "authenticated";
GRANT ALL ON TABLE "public"."football_teams" TO "service_role";



GRANT ALL ON SEQUENCE "public"."football_teams_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."football_teams_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."football_teams_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."hotels" TO "anon";
GRANT ALL ON TABLE "public"."hotels" TO "authenticated";
GRANT ALL ON TABLE "public"."hotels" TO "service_role";



GRANT ALL ON TABLE "public"."live_events" TO "anon";
GRANT ALL ON TABLE "public"."live_events" TO "authenticated";
GRANT ALL ON TABLE "public"."live_events" TO "service_role";



GRANT ALL ON TABLE "public"."locations" TO "anon";
GRANT ALL ON TABLE "public"."locations" TO "authenticated";
GRANT ALL ON TABLE "public"."locations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."offline_hotel_rooms" TO "anon";
GRANT ALL ON TABLE "public"."offline_hotel_rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."offline_hotel_rooms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."offline_hotel_rooms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."offline_hotel_rooms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."offline_hotel_rooms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."offline_hotels" TO "anon";
GRANT ALL ON TABLE "public"."offline_hotels" TO "authenticated";
GRANT ALL ON TABLE "public"."offline_hotels" TO "service_role";



GRANT ALL ON SEQUENCE "public"."offline_hotels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."offline_hotels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."offline_hotels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."p1_events" TO "anon";
GRANT ALL ON TABLE "public"."p1_events" TO "authenticated";
GRANT ALL ON TABLE "public"."p1_events" TO "service_role";



GRANT ALL ON TABLE "public"."partners" TO "anon";
GRANT ALL ON TABLE "public"."partners" TO "authenticated";
GRANT ALL ON TABLE "public"."partners" TO "service_role";



GRANT ALL ON TABLE "public"."reservations" TO "anon";
GRANT ALL ON TABLE "public"."reservations" TO "authenticated";
GRANT ALL ON TABLE "public"."reservations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reservations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reservations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reservations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tixstock_events" TO "anon";
GRANT ALL ON TABLE "public"."tixstock_events" TO "authenticated";
GRANT ALL ON TABLE "public"."tixstock_events" TO "service_role";



GRANT ALL ON TABLE "public"."xs2e_events" TO "anon";
GRANT ALL ON TABLE "public"."xs2e_events" TO "authenticated";
GRANT ALL ON TABLE "public"."xs2e_events" TO "service_role";



GRANT ALL ON TABLE "public"."xs2e_sports" TO "anon";
GRANT ALL ON TABLE "public"."xs2e_sports" TO "authenticated";
GRANT ALL ON TABLE "public"."xs2e_sports" TO "service_role";



GRANT ALL ON TABLE "public"."xs2e_tournaments" TO "anon";
GRANT ALL ON TABLE "public"."xs2e_tournaments" TO "authenticated";
GRANT ALL ON TABLE "public"."xs2e_tournaments" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























